Compiled from asdf.f
public class ExceptionTable extends java.lang.Object {
    public ExceptionTable();
    public static void a(int) throws java.io.IOException, java.lang.ArithmeticException;
    public static void main(java.lang.String[]);
}

Method ExceptionTable()
   0 aload_0
   1 invokespecial #11 <Method java.lang.Object()>
   4 return

Method void a(int)
   0 iload_0
   1 ifne 14
   4 new #15 <Class java.io.IOException>
   7 dup
   8 ldc #20 <String "io exception">
  10 invokespecial #23 <Method java.io.IOException(java.lang.String)>
  13 athrow
  14 iload_0
  15 iconst_1
  16 if_icmpne 29
  19 new #18 <Class java.lang.ArithmeticException>
  22 dup
  23 ldc #25 <String "arithmetic exception">
  25 invokespecial #26 <Method java.lang.ArithmeticException(java.lang.String)>
  28 athrow
  29 return

Method void main(java.lang.String[])
   0 iconst_0
   1 invokestatic #30 <Method void a(int)>
   4 goto 16
   7 astore_1
   8 getstatic #36 <Field java.io.PrintStream out>
  11 ldc #38 <String "caught io exception">
  13 invokevirtual #43 <Method void println(java.lang.String)>
  16 iconst_1
  17 invokestatic #30 <Method void a(int)>
  20 goto 33
  23 astore_2
  24 getstatic #36 <Field java.io.PrintStream out>
  27 ldc #45 <String "caught arithmetic exception">
  29 invokevirtual #43 <Method void println(java.lang.String)>
  32 return
  33 getstatic #36 <Field java.io.PrintStream out>
  36 ldc #47 <String "after handler">
  38 invokevirtual #43 <Method void println(java.lang.String)>
  41 return
Exception table:
   from   to  target type
     0     4     7   <Class java.io.IOException>
    16    20    23   <Class java.lang.ArithmeticException>
